version: "3.7"

services:
  elitedash:
    image: elitedash-elite:latest
    build: .
    networks:
      - typebotnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - io.portainer.accesscontrol.users=admin
        - traefik.enable=true
        - traefik.http.routers.elitedash.rule=Host(`dashinstagram.automatech.tech`)
        - traefik.http.routers.elitedash.entrypoints=web,websecure
        - traefik.http.routers.elitedash.tls.certresolver=letsencryptresolver
        - traefik.http.services.elitedash.loadbalancer.server.port=80
        - traefik.http.services.elitedash.loadbalancer.passHostHeader=true
        - traefik.http.routers.elitedash.service=elitedash

networks:
  typebotnet:
    external: true
    name: typebotnet
